### PR TITLE
New scripts

### PR DESCRIPTION
**Pull request by smehringer**
Todos:
- [ ] make type of document a parameter
- [ ] make time range a parameter 
- [ ] Add OpenMS log file support

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Cool!
Two questions:
- Can we have a parameter for the type of document? If I run this on a light docker container, I might not want to have latex installed and want an html report instead.
- We actually have access to the raw log files on our Jenkins now. Could you make the script accept non-zip files or a folder again? We basically start with the "log.gz" files. But I can extract them on my own.

**Comment by smehringer** [comment]
I'll try but it should be possible. 

I can reverse the unzipping in the script. Can you give an exact example of how the directory and file(s) will look? are there multiple files? multiple directories? how is the naming? are they always gzipped?

I also managed to automatically include the worldmap plot, but it might be in a state that "only works on my machine". Can you set up a Jenkins Job according to the new documentation? (and maybe even include it as CI for this repo? It would be helpful to automatically know if the scripts run on the docker)

**Comment by jpfeuffer** [comment]
Yes ok!
Jenkins job is here: https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_general_usageStatistics/
Tell me if you have access.
I will connect it to this repo.
The logs are I think .1.log, .2.log.gz, .3.log.gz etc. but I will unpack them and if you want, concat them.

**Comment by smehringer** [comment]
I've never really worked with Jenkins so far... where do I find the script that is run for the jobs? I can view the builds but I cannot access any file that would permit me to change something (or at least I don't see where)?

**Comment by smehringer** [comment]
!rebuild

**Comment by smehringer** [comment]
!rebuild

**Comment by jpfeuffer** [comment]
Seems like not all the seqan logs are accessible.

**Comment by jpfeuffer** [comment]
But this is not the problem. It should work on the rest of the log files.

`./process_seqan_log_files.sh: line 21: syntax error near unexpected token 'fi'`

**Comment by jpfeuffer** [comment]
Seems to run better. I suggest to use html for now, unless you want to update the setup script to also install latex.

**Comment by jpfeuffer** [comment]
Cool last run seemed to work. Where will the results be located? I would like to save and upload them somehow.

**Comment by jpfeuffer** [comment]
Three problems:
- Worldmap empty
- Security problems with displaying the html online (low priority, works offline)
- `./process_seqan_log_files.sh: line 18: [[: 303176 ./seqan-update_access_all.log: syntax error: invalid arithmetic operator (error token is "./seqan-update_access_all.log")`

**Comment by smehringer** [comment]
!rebuild

**Comment by smehringer** [comment]
!rebuild

**Comment by smehringer** [comment]
!rebuild

**Comment by jpfeuffer** [comment]
rebuild jenkins

**Comment by jpfeuffer** [comment]
haha you are right. it's ! rebuild here.

**Comment by smehringer** [comment]
How do I add python to the jenkins build?
I updated the database but the build fails because 
`./process_seqan_log_files.sh: line 57: python: command not found` 
I thought stuff like python is installed...

**Comment by smehringer** [comment]
!rebuild

**Comment by smehringer** [comment]
!rebuild

**Comment by jpfeuffer** [comment]
Yes. Great. Works.

**Pull request merged**
